### ISSUE TITLE
Support for JAR files

### ISSUE THREAD

**Issue by ax-vasquez** [nuggylib/minecraft-asset-reader#41]
# Description

When this project started, we wanted to keep things simple. Now, we are ready to make things a bit more flexible.

Once #40 is complete, we should modify that logic so that it accepts a path to any of the following valid JAR files:
1. Minecraft game
2. Minecraft mod
3. Minecraft modpack

The logic for each will vary slightly.

## Minecraft game / Minecraft mod

The logic for these is about the same; we simply need to check if there is an `assets` directory in the JAR file. If there is, we can go forward with processing.

## Minecraft modpack

This is a bit more complicated - we would need to search the `mods` folder of the specified JAR file and, _for each mod_, search for the `assets` directory; for all mods detected with an `assets` directory, import the data as usual

> TODO: I would like to eventually support _all_ files; it seems like it might be easy to do. I would think that, when we can't find the `assets` directory, just search for the directories we would normally look for in there at the root of the JAR file. Older versions of the game have directories like `blocks`, `items`, etc. at the root of the JAR file.

**Comment by armstrongl** [comment]
Closed in favor of #73
